[workspace]
resolver = "2"
members = [
  "mwp-web",
  "mwp-scraper",
  "mwp-content",
  "mwp-search",
]

default-members = [
  "mwp-web"
]

[profile.release]
lto = "thin"

[workspace.package]
name = "mwp"
version = "0.1.0"
edition = "2021"
authors = ["Matouš Dzivjak <matousdzivjak@gmail.com>"]
categories = ["wiki", "knowledge-bage"]
repository = "https://github.com/matoous/mwp"
homepage = "https://github.com/matoous/mwp"
rust-version = "1.70"
