# fly.toml app configuration file generated for mwp on 2024-03-04T11:18:35+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mwp'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 4444
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
