[package]
name = "xtask"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.24", features = [
  "derive",
  "string",
  "env",
  "wrap_help",
] }
pretty_env_logger = "0.5.0"

tokio = { workspace = true }

mwp-scraper = { path="../mwp-scraper" }
