[package]
name = "xtask"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.23", features = [
  "derive",
  "string",
  "env",
  "wrap_help",
] }
tokio = { version = "1.42.0", features= ["full"]}

mwp-scraper = { path="../mwp-scraper" }
