[package]
name = "mwp-content"
authors.workspace = true
version.workspace = true
edition.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
pulldown-cmark = "0.13.0"
url = "2.5.4"
walkdir = "2.5.0"
