[package]
name = "mwp-web"
authors.workspace = true
version.workspace = true
edition.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
actix-files = "0.6.5"
actix-web = "4.4.1"
env_logger = "0.10.1"
maud = { version = "0.25.0", features = ["actix-web"] }
serde = "1.0.195"
serde_json = "1.0.111"
tantivy = "0.21.1"

mwp-content = { path="../mwp-content" }

[build-dependencies]
grass = "0.13.1"
