[package]
name = "mwp-scraper"
authors.workspace = true
version.workspace = true
edition.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
html-escape = "0.2.13"
lazy_static = "1.4.0"
lol_html = "1.2.0"
regex = "1.10.2"
reqwest = "0.11.24"
url = "2.5.0"
